import type { Metadata } from "next";
import Image from "next/image";
import { Container } from "../../_components/Container";
import { Kicker } from "../../_components/Kicker";
import { Button } from "../../_components/Button";
import { StatBlock } from "../../_components/StatBlock";
import { KenteDivider } from "../../_components/KenteDivider";

export const metadata: Metadata = {
  title: "Vedge Staff — the companion app for every clinician",
  description: "The Android and iOS companion to Vedge. Role-adaptive: doctors see their queue, nurses their MAR, lab techs their bench. Offline-first, built for the wards you actually work in.",
};

// ---------------------------------------------------------------------------
// Role-by-role capability matrix. Each role shows the app surfaces relevant
// to their shift — what they'd open the phone for on a random Tuesday.
// ---------------------------------------------------------------------------

type RoleCapability = {
  kicker: string;
  title: string;
  tagline: string;
  features: string[];
  accent: "doctor" | "nurse" | "lab" | "pharmacy" | "reception" | "admin";
};

const roles: RoleCapability[] = [
  {
    kicker: "R01",
    title: "Doctor",
    tagline: "Your round, in your pocket.",
    accent: "doctor",
    features: [
      "Patient queue sorted by acuity, not arrival",
      "Full chart, vitals trend, and allergies on one tap",
      "Order labs, imaging, and prescriptions from the bedside",
      "Critical-result pages with acknowledgement audit trail",
      "Sign notes with dictation — STT tuned for Ghanaian English",
      "Discharge sheet autogenerated from today\u2019s encounter",
    ],
  },
  {
    kicker: "R02",
    title: "Nurse",
    tagline: "MAR, vitals, triage — without the paper.",
    accent: "nurse",
    features: [
      "Medication Administration Record with barcode + due-now queue",
      "Vitals capture with range-aware alerts (BP, HR, SpO\u2082, temp, pain)",
      "ESI triage with acuity picker and chief-complaint templates",
      "Ward census grouped by ward and bed — today\u2019s census, not the directory",
      "SBAR handoff cards for shift change",
      "Patient search sheet for ad-hoc vitals or notes",
    ],
  },
  {
    kicker: "R03",
    title: "Lab technician",
    tagline: "The bench, without the paper tray.",
    accent: "lab",
    features: [
      "Specimen accessioning with barcode scan",
      "Bench queue sorted by TAT and priority",
      "Result entry with reference-range auto-flag",
      "Critical result escalation with two-person verification",
      "Levey-Jennings QC runs and Westgard-rule violations",
      "Reagent lot tracking and expiry alerts",
    ],
  },
  {
    kicker: "R04",
    title: "Pharmacist",
    tagline: "Dispense, counsel, inventory — from the counter.",
    accent: "pharmacy",
    features: [
      "Dispensing queue fed live from ward and outpatient charts",
      "Drug-drug interaction and allergy checks at pick",
      "Inventory scan with lot + expiry capture",
      "NHIS dispensing with automatic claim generation",
      "Patient counselling checklist per medication class",
      "Controlled drug register with witness sign-off",
    ],
  },
  {
    kicker: "R05",
    title: "Receptionist",
    tagline: "Front desk, even when the queue is out the door.",
    accent: "reception",
    features: [
      "Patient registration in under a minute, insurance captured",
      "Today\u2019s appointment board with no-show tracking",
      "Walk-in triage handoff to the nurse on duty",
      "Queue display and SMS callback",
      "Insurance verification against NHIS and private schemes",
      "Folder-number lookup for legacy paper records",
    ],
  },
  {
    kicker: "R06",
    title: "Org admin",
    tagline: "Runs the shop without leaving the floor.",
    accent: "admin",
    features: [
      "Usage vs plan limits at a glance (staff, locations, patients)",
      "Staff invite, role assignment, and revoke",
      "Audit trail — who touched what, when",
      "Critical alert dashboard across every unit",
      "Subscription and billing status",
      "Force-logout a lost device from anywhere",
    ],
  },
];

// ---------------------------------------------------------------------------
// Engineering principles that make the app work in wards, not demos.
// ---------------------------------------------------------------------------

const principles = [
  {
    code: "OFF",
    name: "Offline-first",
    body: "The app charts, triages, and administers meds when the Wi-Fi drops and the generator dies. Writes queue locally and sync the moment connectivity returns.",
  },
  {
    code: "LOW",
    name: "Low-end ready",
    body: "Runs on ₵1,200 Android phones — not just flagships. Impeller rendering, no heavy animations, and a static-first design system.",
  },
  {
    code: "BIO",
    name: "Biometric lock",
    body: "Fingerprint or face unlock wraps every session. Lost phone? Revoke it from the admin console in seconds — the token is dead instantly.",
  },
  {
    code: "AUD",
    name: "Tamper-evident audit",
    body: "Every chart entry, every med administered, every critical result acknowledged — signed with the user\u2019s token and a monotonic sequence number. No back-dating.",
  },
  {
    code: "TRU",
    name: "Your data, your tenant",
    body: "Hospital data never mixes with another hospital\u2019s. Schema-per-tenant at the database level — enforced, not promised.",
  },
  {
    code: "UPG",
    name: "Over-the-air updates",
    body: "Your matron doesn\u2019t need to re-install when we ship a fix. The app checks for updates every cold start and applies them quietly.",
  },
];

export default function VedgeStaffPage() {
  return (
    <>
      {/* ═══════════════ HERO ═══════════════ */}
      <section className="relative overflow-hidden border-b border-ink/15">
        <div className="grain absolute inset-0" />
        <Container className="relative z-10 pt-20 pb-24 md:pt-28 md:pb-28">
          <div className="grid grid-cols-12 gap-6 md:gap-10">
            <div className="col-span-12 md:col-span-7">
              <Kicker>Companion · Vedge Staff</Kicker>
              <h1 className="reveal mt-6 font-display text-hero">
                Every clinician&rsquo;s <span className="italic-display">companion.</span> Every role&rsquo;s <span className="italic-display">home screen.</span>
              </h1>
              <p className="reveal reveal-delay-1 mt-10 max-w-xl font-display text-lg leading-relaxed text-ink/80">
                The Vedge Staff app adapts to who you are. Doctors see their queue. Nurses see the MAR and ward census. Lab techs see their bench. Pharmacists see the dispensing queue. One app, six home screens, zero training.
              </p>
              <div className="reveal reveal-delay-2 mt-10 flex flex-wrap gap-4">
                <Button href="/contact">Request early access</Button>
                <Button href="#roles" variant="ghost">See what your role gets</Button>
              </div>
              <div className="reveal reveal-delay-2 mt-12 grid grid-cols-3 gap-y-8 md:gap-x-6">
                <StatBlock value="6" label="Role home screens" />
                <StatBlock value="100%" label="Offline capable" />
                <StatBlock value="₵0" label="Add-on cost" />
              </div>
            </div>

            {/* Hero screenshot — real device shot (Samsung G998U on staging). */}
            <div className="col-span-12 md:col-span-5">
              <div className="relative mx-auto w-full max-w-[280px] md:max-w-none">
                <div className="reveal reveal-delay-1 relative rounded-[2.5rem] border border-ink/15 bg-ink/5 p-3 shadow-[8px_8px_0_0_rgba(11,11,9,0.9)]">
                  <Image
                    src="/screenshots/nurse-home.png"
                    alt="Nurse home screen on Vedge Staff showing today's shift, 3 counter cards, and medications due now."
                    width={1080}
                    height={2400}
                    priority
                    className="rounded-[1.75rem]"
                  />
                </div>
                <p className="mt-5 text-center font-mono text-[10px] uppercase tracking-kicker text-ink/60">
                  Nurse · Day shift · Ridge Hospital
                </p>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* ═══════════════ ROLES ═══════════════ */}
      <section id="roles" className="py-24 md:py-32">
        <Container>
          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-12 md:col-span-4">
              <Kicker>Roles</Kicker>
              <h2 className="reveal mt-6 font-display text-display">
                One app. <br /><span className="italic-display">Six people.</span>
              </h2>
              <p className="reveal reveal-delay-1 mt-6 max-w-sm text-ink/70">
                The wrong nav item on a phone costs shift time. We build a separate home for every role so your hand lands where it needs to, first try.
              </p>
            </div>
            <div className="col-span-12 md:col-span-8">
              <ul className="grid grid-cols-1 border-t border-ink/20">
                {roles.map((role, i) => (
                  <li
                    key={role.kicker}
                    className="reveal border-b border-ink/15 py-8"
                    style={{ transitionDelay: `${0.06 * i}s` }}
                  >
                    <div className="grid grid-cols-12 gap-4">
                      <div className="col-span-12 md:col-span-3">
                        <div className="font-mono text-[10px] uppercase tracking-kicker text-clay">
                          {role.kicker}
                        </div>
                        <h3 className="mt-2 font-display text-2xl">{role.title}</h3>
                        <p className="mt-2 font-display italic text-sm text-ink/70">{role.tagline}</p>
                      </div>
                      <ul className="col-span-12 md:col-span-9 grid grid-cols-1 gap-2 sm:grid-cols-2">
                        {role.features.map((feature) => (
                          <li
                            key={feature}
                            className="flex items-start gap-3 text-sm leading-relaxed text-ink/80"
                          >
                            <span className="mt-[6px] inline-block h-1 w-4 flex-none bg-clay" />
                            <span>{feature}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Container>
      </section>

      <KenteDivider className="bg-bone-deep py-4" />

      {/* ═══════════════ SCREENSHOT SHOWCASE ═══════════════ */}
      <section className="bg-bone-deep py-24 md:py-32">
        <Container>
          <div className="grid grid-cols-12 gap-10">
            <div className="col-span-12 md:col-span-4">
              <Kicker>Real screens</Kicker>
              <h2 className="reveal mt-6 font-display text-display">
                Not mock-ups. <br /><span className="italic-display">Ship-ready.</span>
              </h2>
              <p className="reveal reveal-delay-1 mt-6 max-w-sm text-ink/70">
                Every screen here is a build straight from our CI pipeline, running on a staff member&rsquo;s phone against a live Ridge Hospital tenant. No placeholders.
              </p>
            </div>

            <div className="col-span-12 md:col-span-8 grid gap-10 sm:grid-cols-2">
              <figure className="reveal">
                <div className="relative rounded-[2rem] border border-ink/15 bg-bone p-3">
                  <Image
                    src="/screenshots/nurse-home.png"
                    alt="Nurse home screen showing date and shift, three counter cards, action pills, and a live medications-due section."
                    width={1080}
                    height={2400}
                    className="rounded-[1.5rem]"
                  />
                </div>
                <figcaption className="mt-5">
                  <div className="font-mono text-[10px] uppercase tracking-kicker text-clay">
                    Home · Nurse
                  </div>
                  <p className="mt-2 font-display text-lg leading-tight">
                    Counters that matter to a nurse on shift — meds due, vitals due, tasks pending. Not a generic dashboard.
                  </p>
                </figcaption>
              </figure>

              <figure className="reveal reveal-delay-1">
                <div className="relative rounded-[2rem] border border-ink/15 bg-bone p-3">
                  <Image
                    src="/screenshots/nurse-ward.png"
                    alt="Ward tab showing admitted patients grouped by ward, with bed-number badges, admission reason, and attending provider."
                    width={1080}
                    height={2400}
                    className="rounded-[1.5rem]"
                  />
                </div>
                <figcaption className="mt-5">
                  <div className="font-mono text-[10px] uppercase tracking-kicker text-clay">
                    Ward · Inpatient census
                  </div>
                  <p className="mt-2 font-display text-lg leading-tight">
                    Active admissions grouped by ward. Bed A-01, Akosua Addo, day 1 post-op — exactly the question on a nurse&rsquo;s lips.
                  </p>
                </figcaption>
              </figure>
            </div>
          </div>
        </Container>
      </section>

      {/* ═══════════════ ENGINEERING PRINCIPLES ═══════════════ */}
      <section className="py-24 md:py-32">
        <Container>
          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-12 md:col-span-4">
              <Kicker>How it&rsquo;s built</Kicker>
              <h2 className="reveal mt-6 font-display text-display">
                Built for the <br /><span className="italic-display">wards you work in.</span>
              </h2>
              <p className="reveal reveal-delay-1 mt-6 max-w-sm text-ink/70">
                We tested on the cheapest Android phone you can buy in Accra, on a ward with a flaky Wi-Fi router and a nightly power cut. That&rsquo;s the baseline.
              </p>
            </div>
            <div className="col-span-12 md:col-span-8">
              <ul className="grid grid-cols-1 border-t border-ink/20 sm:grid-cols-2">
                {principles.map((p, i) => (
                  <li
                    key={p.code}
                    className={`reveal border-b border-ink/15 p-7 ${i % 2 === 0 ? "sm:border-r sm:border-ink/15" : ""}`}
                    style={{ transitionDelay: `${0.06 * i}s` }}
                  >
                    <div className="font-mono text-[10px] uppercase tracking-kicker text-clay">{p.code}</div>
                    <h3 className="mt-3 font-display text-2xl">{p.name}</h3>
                    <p className="mt-3 text-sm leading-relaxed text-ink/70">{p.body}</p>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Container>
      </section>

      {/* ═══════════════ PULL QUOTE ═══════════════ */}
      <section className="bg-bone-deep py-28 md:py-36">
        <Container>
          <div className="mx-auto max-w-4xl">
            <p className="reveal font-display text-mega leading-none text-ink/15">&ldquo;</p>
            <p className="reveal reveal-delay-1 -mt-16 font-display text-display leading-[1.05]">
              I stopped carrying the paper MAR in my pocket. <span className="italic-display">The phone does it now — and doesn&rsquo;t get wet when I wash my hands.</span>
            </p>
            <p className="reveal reveal-delay-2 mt-10 font-mono text-[11px] uppercase tracking-kicker text-ink/60">
              — Staff nurse · Paediatric ward
            </p>
          </div>
        </Container>
      </section>

      {/* ═══════════════ CTA ═══════════════ */}
      <section className="border-t border-ink/15 bg-forest-deep text-bone">
        <Container className="py-24 md:py-32">
          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-12 md:col-span-8">
              <Kicker className="!text-sun">Early access</Kicker>
              <h2 className="reveal mt-8 font-display text-hero text-bone">
                Android first. <span className="italic-display !text-sun">iOS soon.</span>
              </h2>
              <p className="reveal reveal-delay-1 mt-6 max-w-xl text-bone/75">
                Included with every Vedge subscription. No separate price, no per-seat fee for the app. Start a trial and we&rsquo;ll send your matron the APK by the time your bed board is wired.
              </p>
            </div>
            <div className="col-span-12 mt-8 md:col-span-4 md:mt-0 md:flex md:items-end md:justify-end">
              <Button href="/contact" variant="ghost" className="!border-bone/40 !text-bone hover:!bg-bone hover:!text-forest-deep">
                Request early access
              </Button>
            </div>
          </div>
        </Container>
      </section>
    </>
  );
}
